### ISSUE TITLE
Edit screen showing terms in all languages

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-wpml#1]
Help Scout #2387

> When Facet WPML plugin is activated, when adding a new post the list of Categories shows both the EN and FR terms. If I disable Facet WPML then the Add Post page just shows the term for correct language.

Help Scout #2444

> When FacetWP's WPML extension is enabled and I create a new post the taxonomies in the taxonomy list will display all translations. This issue does not appear after saving this new post. It only happens when creating new post not when editing old ones.

**Comment by blueeclipse** [comment]
Going through the code I've determined the line causing the issue is $GLOBALS['sitepress']->switch_lang( 'all' );

` function indexer_query_args( $args ) {
	$GLOBALS['sitepress']->switch_lang( 'all' );
        $args['suppress_filters'] = true; // query posts in all languages
        return $args;
    }`

**Comment by mgibbs189** [comment]
Thanks, that's helpful. I'll look into `switch_lang` more closely to see what's going on.

**Comment by mgibbs189** [comment]
@blueeclipse in `/plugins/facetwp/includes/class-index.php`, line ~ 42, could you try adding the following code?

```php
        if ( 'auto-draft' == get_post_type( $post_id ) ) {
            return;
        }
```

Screenshot: http://d.pr/i/8jsa

Does this fix the issue?

**Comment by blueeclipse** [comment]
@mgibbs189 No dice. 

If I comment out this line `$this->index( $post_id );` the issue is resolved...

**Comment by mgibbs189** [comment]
@blueeclipse Oops, mistake on my part. In the above code, `get_post_type` needed to be `get_post_status`. Try that instead, thanks.

**Comment by blueeclipse** [comment]
@mgibbs189 Yes that seems to solve it

**Comment by mgibbs189** [comment]
@blueeclipse Awesome, thanks for your help. I'll roll this into the next version of FacetWP.

**Comment by pcfrancky** [comment]
Hi there, i've a similar issue with plugins Job Manager (listify theme) + WPML + FacetWP (last versions).
Since I've actived FacetWP, the filters have replaced the Job manager ones on the homepage (loctim.com) and on the search page. That's ok but the "category" filter displays now all languages instead of the category from the choosen language. I've tried to modify your php file but nothing has changed. Please help ;-)

**Comment by mgibbs189** [comment]
@pcfrancky is this when using v1.1 of the add-on?

**Comment by pcfrancky** [comment]
Hi, yes it's FaceWP -WPML 1.1 with FACEWP 2.4.
The listify template works well before i set on this FaceWP's plugins. I mean, the categories change when i change the language. I must to make a mistake somewhere but i do not know what.
See the image below with the categories field which show different languages instead of the english only :
![facewp](https://cloud.githubusercontent.com/assets/17628429/13559904/f69dc484-e410-11e5-83b2-8dfa808eb63c.jpg)
